sudo: required
language: python
python:
    - "3.6"
    - "3.9"
before_install:
    - sudo apt-get install python3-psycopg2
    - sudo apt-get install postgresql
    - sudo -u postgres createuser root
    - sudo -u postgres cretedb -O root pr2test
script: sudo make pytest
