dist: bionic
sudo: required
language: python
services:
    - postgresql
addons:
    postgresql: "13"
    apt:
      packages:
        - postgresql-13
        - postgresql-server-dev-13
env:
    global:
        - PGPORT=5433
        - PGUSER=postgres
before_install:
    - >-
      sudo sed -i
      -e '/local.*peer/s/postgres/all/'
      -e 's/peer\|md5/trust/g'
      /etc/postgresql/13/main/pg_hba.conf
    - sudo systemctl restart postgresql@13-main
before_script:
    - psql -p 5433 -U postgres -c 'create database pr2test;'
python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
script: sudo env PATH=$PATH VIRTUAL_ENV=$VIRTUAL_ENV make pytest
